import assert from 'node:assert/strict';
globalThis.window={addEventListener(){},STATE:null};
globalThis.document={addEventListener(){},querySelectorAll(){return[]},querySelector(){return null},getElementById(){return null},createElement(){return {style:{},classList:{add(){},remove(){}},setAttribute(){},appendChild(){},querySelector(){return null}}}};
globalThis.localStorage={getItem(){return null},setItem(){},removeItem(){}};globalThis.requestAnimationFrame=f=>f();globalThis.getComputedStyle=()=>({position:'static'});
const m=await import(new URL('../js/matches4.js',import.meta.url));
for(const n of ['initMatches','updateMatchDom','getMissingGroupBets','getMissingKnockoutDecisionsCount','saveLocalDraft','clearLocalDraft','loadLocalDraft','buildSavePayload']) assert.equal(typeof m[n],'function',`missing export ${n}`);
for(const n of ['renderMatches','renderKnockoutMatches','toggleKnockoutPendingFilter','togglePendingFilter','setMatchFilter','setKnockoutFilter','syncModalData','renderLineups','renderAbaEstatisticas','abrirDetalhesPartida','switchTab','unlockMatchForEdit','saveSingleBet','syncEngravedFlags']) assert.equal(typeof window[n],'function',`missing global ${n}`);
let groupRenderCalls=0, knockoutRenderCalls=0;
const originalGroupRender=window.renderMatches;
const originalKnockoutRender=window.renderKnockoutMatches;
window.renderMatches=()=>{groupRenderCalls++; return originalGroupRender?.();};
window.renderKnockoutMatches=()=>{knockoutRenderCalls++; return originalKnockoutRender?.();};
window.STATE.matches=[]; window.STATE.hasSubmitted=true;
window.togglePendingFilter(true); window.toggleKnockoutPendingFilter(true); window.setMatchFilter('date'); window.setKnockoutFilter('date');
window.renderMatches(); window.renderKnockoutMatches();
assert.equal(window.STATE.groupStatusFilter,'pending'); assert.equal(window.STATE.knockoutStatusFilter,'pending'); assert.equal(window.STATE.groupFilter,'date'); assert.equal(window.STATE.knockoutFilter,'date');
assert.equal(groupRenderCalls >= 1,true,'group render wrapper not called');
assert.equal(knockoutRenderCalls >= 1,true,'knockout render wrapper not called');
console.log('MATCHES_REFACTOR_RUNTIME_OK');
