import assert from 'node:assert/strict';
const wrap={innerHTML:'',querySelectorAll(){return[]},querySelector(){return null}};
globalThis.window={addEventListener(){},STATE:null,syncEngravedFlags(){}};
globalThis.document={addEventListener(){},querySelectorAll(){return[]},querySelector(sel){return sel==='#matches-container'?wrap:null},getElementById(){return null},createElement(){return {style:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},appendChild(){},querySelector(){return null},querySelectorAll(){return[]}}}};
globalThis.localStorage={getItem(){return null},setItem(){},removeItem(){}};
globalThis.requestAnimationFrame=f=>f(); globalThis.getComputedStyle=()=>({position:'static'});
await import(new URL('../js/matches4.js',import.meta.url));
window.STATE.matches=[{matchId:2,phase:'group',group:'B',status:'1_tempo',minute:35,teamA:'Brazil',teamB:'Argentina',scoreA:1,scoreB:0,logoA:'',logoB:''}];
window.STATE.hasSubmitted=true;
window.STATE.scoringRules={exactScore:5,scoreTeamA:1,scoreTeamB:1,winner:2,qualifier:3,podiumPoints:[20,15,10,5]};
window.STATE.betsMap.set(2,'A'); window.STATE.scoresMap.set(2,{scoreA:1,scoreB:0});
assert.doesNotThrow(()=>window.renderMatches([]));
assert.ok(wrap.innerHTML.includes('Brazil'),'live group match rendered');
console.log('LIVE_GROUP_RENDER_OK');
