import assert from 'node:assert/strict';
const wrap={innerHTML:'',querySelectorAll(){return[]},querySelector(){return null}};
globalThis.window={addEventListener(){},STATE:null};
globalThis.document={addEventListener(){},querySelectorAll(){return[]},querySelector(sel){return sel==='#matches-container'?wrap:null},getElementById(){return null},createElement(){return {style:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},appendChild(){},querySelector(){return null},querySelectorAll(){return[]}}}};
globalThis.localStorage={getItem(){return null},setItem(){},removeItem(){}};
globalThis.requestAnimationFrame=f=>f(); globalThis.getComputedStyle=()=>({position:'static'});
const m=await import(new URL('../js/matches4.js',import.meta.url));
window.STATE.matches=[{matchId:1,phase:'group',group:'A',status:'finished',teamA:'Brazil',teamB:'Argentina',scoreA:2,scoreB:1,logoA:'',logoB:''}];
window.STATE.hasSubmitted=true;
window.STATE.scoringRules={exactScore:5,scoreTeamA:1,scoreTeamB:1,winner:2,qualifier:3};
window.STATE.betsMap.set(1,'A');
window.STATE.scoresMap.set(1,{scoreA:2,scoreB:1});
assert.doesNotThrow(()=>window.renderMatches([]));
assert.ok(wrap.innerHTML.includes('Brazil'),'finished group match rendered');
console.log('FINISHED_GROUP_RENDER_OK');
